In [ ]:
!pip3 install numpy


In [ ]:
import numpy as np


In [ ]:
import time
size =1000000
l1=list(range(size))
l2=list(range(size))

start= time.time()
res=[]
for i in range (size):
  res.append(l1[i]+l2[i])
end=time.time()
print('time tazken byb python list' ,end-start)

time tazken byb python list 0.23656558990478516


In [ ]:
array1= np.arange(size)
array2= np.arange(size)

start2=time.time()
result=array1+array2
end2= time.time()
print("time taken by num py,",end2-start2)

time taken by num py, 0.0160367488861084


In [ ]:
#checking datatype of array --> int 64 , int 32,
np.dtype(array1)

TypeError: Cannot construct a dtype from an array

In [ ]:
# formation of 1d array
arr1d=np.array([1,2,3,4,5,6])
arr1d


array([1, 2, 3, 4, 5, 6])

In [ ]:
#formation of 2D array--> need atleast two 1D array
arr2d=np.array([[1,2,3,4,5,6],
                [2,3,4,5,6,7],
                [23,45,67,78,98,21]])
arr2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  3,  4,  5,  6,  7],
       [23, 45, 67, 78, 98, 21]])

In [ ]:
#formation of 3D array  --> need atleast two 3d array
array3D=np.array([
           [[1,2,34,4,2],
             [2,43,4,65,3]],
          [[11,22,33,44,55],[11,22,44,66,77]],
           [[11,4.3,56,87,99],[11,22,33,44,55]]])
array3D

array([[[ 1. ,  2. , 34. ,  4. ,  2. ],
        [ 2. , 43. ,  4. , 65. ,  3. ]],

       [[11. , 22. , 33. , 44. , 55. ],
        [11. , 22. , 44. , 66. , 77. ]],

       [[11. ,  4.3, 56. , 87. , 99. ],
        [11. , 22. , 33. , 44. , 55. ]]])

In [ ]:
#checking dimension of an array--> .ndim
print(f"array: dimension:{arr1d.ndim}")
print(f"array: dimension:{arr2d.ndim}")
print(f"array: dimension:{array3D.ndim}")

array: dimension:1
array: dimension:2
array: dimension:3


In [ ]:
#checking the shape of array-->(num of row,num of col)--> .shape
print(f"array:shape:{arr1d.shape}")
print(f"array:shape:{arr2d.shape}")
print(f"array:shape:{array3D.shape}")#()

array:shape:(6,)
array:shape:(3, 6)
array:shape:(3, 2, 5)


In [ ]:
print(f"array: total num ber of elements: {arr1d.size}")
print(f"array:shape:{arr2d.size}")
print(f"array:shape:{array3D.size}")#()

array: total num ber of elements6
array:shape:18
array:shape:30


In [ ]:
#converting array into another datatype --> astype('type')
arr_ex=np.array([1,2,3,4,5,6,7,8,9])
print(arr_ex)
print()
print('daty type of arr_ex',arr_ex.dtype)
print()
arr_new=arr_ex.astype(float)
print()
print('daty type of arr_ex',arr_new.dtype)
print()
arr_new

[1 2 3 4 5 6 7 8 9]

daty type of arr_ex int64


daty type of arr_ex float64



array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#Converting array into different shapes --> .reshape(rows,columns)
#by default filling of element will be row-wise
arr_exm=np.array([1,2,3,4,56,7,89,9,12,11])
print(arr_exm)



[ 1  2  3  4 56  7 89  9 12 11]


In [ ]:
arr_exm.reshape(5,2)


array([[ 1,  2],
       [ 3,  4],
       [56,  7],
       [89,  9],
       [12, 11]])

In [ ]:
arr_exm.reshape((5,2),order='F') # Fortran order --> column major order

array([[ 1,  7],
       [ 2, 89],
       [ 3,  9],
       [ 4, 12],
       [56, 11]])

In [ ]:
import numpy as np

In [ ]:
a =  np.array(42)  # 0-D
b = np.array([1,2,3,4,5])  # 1-D
c = np.array([[1,2,3],[4,5,6]])  # 2-D
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])  #3-D


print("dimension of a is: ", a.ndim)
print("dimension of b is: ", b.ndim)
print("dimension of c is: ", c.ndim)
print("dimension of d is: ", d.ndim)

dimension of a is:  0
dimension of b is:  1
dimension of c is:  2
dimension of d is:  3


In [ ]:
#indexing
#1D--> array[index]
array1d=np.array([1,2,3,4,5,6,7],)
array1d
print(array1d[4])

5


In [ ]:
#for 2d--> arraey[row , index]
array2d=np.array([[1,2,3,4],[11,22,33,44],[55,66,77,88]])
print(array2d[1,2])
print(array2d[0,2])
print(array2d[2,2])

33
3
77


In [ ]:
#for 3d--> arraey[index of_ [matriex,row , index]
array3D=np.array([[
    [1,2,3,4],[5,6,7,8]
    ],
     [[11,22,33,44],[55,66,77,88]
      ]
                  ])
print(array3D[1,0,2])
print(array3D[0,1,1])
print(array3D[1,1,1])


33
6
66


In [ ]:
#slicing of arrays
#1d--> array[index_num:index_num2+1]
array1d=np.array([1,2,3,4,5,6,7],)
array1d
print(array1d[1:4])
print(array1d[4:])

[2 3 4]
[5 6 7]


In [ ]:
#slicing of arrays
#2d--> array[index_num:index_num2+1]
array2d=np.array([[1,2,3,4],[11,22,33,44],[55,66,77,88]])
print(array2d[1,1:3])
print(array2d[0,:3])
print(array2d[2,1:])

[22 33]
[1 2 3]
[66 77 88]


In [ ]:
#slicing of arrays
#3d--> array[index_num:index_num2+1]
array3D=np.array([[
    [1,2,3,4],[5,6,7,8]
    ],
     [[11,22,33,44],[55,66,77,88]
      ]
                  ])
print(array3D[0,1,2:])
print(array3D[1,1,2:])

[7 8]
[77 88]


In [ ]:
#making the basic numpy array
import numpy as np
a=np.array(range(20),dtype="float",ndmin=5)
print(a)

[[[[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.
     16. 17. 18. 19.]]]]]


In [ ]:
#indexing based on certain condition -->
#array [mask]
#create a array
x=np.array([1,2,3,46,6,7,8,9,10,11,12,13,14])
mask=(x%2==0)
print(x[mask])

[ 2 46  6  8 10 12 14]


In [ ]:
#filter out those element which are divisibal by two and positive
y=np.array([-1,1,2,3,4,5,6,-6,-7,11,12,-13,-14,15,16])
mask2=(y%2==0)&(y>0)
print(y[mask2])

[ 2  4  6 12 16]


In [ ]:
#filter out those element which are divisibal by two or three
y=np.array([-1,1,2,3,4,5,6,-6,-7,11,12,-13,-14,15,16])
mask2=(y%2==0)|(y%3==0)
print(y[mask2])

[  2   3   4   6  -6  12 -14  15  16]


In [ ]:
#arange () it can be used with float datatype
x=np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#arange () it can be used with float datatype if you use rannge in float datatype it will give me error
x=np.arange(1,11.5)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
#np.linespace(start ,stop,number)-->generater the array with equal spacing between
np.linspace(0,1,11)
#generate 11 number between 0 and 1 with liner spacing

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
np.linspace(1,25,5)

array([ 1.,  7., 13., 19., 25.])

In [ ]:
#creating ones matrix
#creating 3*3matrix  where the value are 1
np.ones((3,3),int)
#np.ones((4,2),int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
#creating zeros matrix
np.zeros((4,2),int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
#creating indentity matrix --> a matrix diagonal elementa are 1
#np.eye(row,column)
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#creating the empty matrix #use for testing for time saving
#matrix of random values --> faster the np.zeros and ones
#np.empty(row ,column),dtype =optional
np.empty((3,3),dtype=int)
np.empty((3,3),dtype=int)

array([[73888576,        0,        0],
       [       0,        0,        0],
       [       0,        0,        0]])

In [ ]:
#sum function --> sum of all the elemenmts
#np.sum(array)
array2D=np.array([[1,2,3,4],[5,5,6,7],[8,8,7,9]])
np.sum(array2D)

np.int64(65)

In [ ]:
#create numpy arrary with prefilled with some specific number
pre_array=np.full(5,5)#create an array with 10 elements where each elements ids 5
print(pre_array)

[5 5 5 5 5]


In [ ]:
#for row wise addition
array2D=np.array([[1,2,3,4],[5,5,6,7],[8,8,7,9]])
array2D

array([[1, 2, 3, 4],
       [5, 5, 6, 7],
       [8, 8, 7, 9]])

In [ ]:
##for row wise addition
#axis=0--> row
#axis=1-->column
np.sum(array2D,axis=0)

array([14, 15, 16, 20])

In [ ]:
np.sum(array2D,axis=1)

array([10, 23, 32])

In [ ]:
import numpy as np

In [ ]:
#finding min array
x=np.array([500,400,200,600,700])
print('min ',np.min(x))
print('max ',np.max(x))

min  200
max  700


In [ ]:
#to get index location of min and max value
print('index location of min and max value:',np.argmin(x))
print('index location of min and max value:',np.argmax(x))

index location of min and max value: 2
index location of min and max value: 4


In [ ]:
array2D=np.array([[1,2,3,4],[5,5,6,7],[8,8,7,9]])
array2D
print('min ',np.min(array2D))
print('max ',np.max(array2D))
print('index location of min and max value:',np.argmax(array2D))

min  1
max  9
index location of min and max value: 11


In [ ]:
array3D=np.array([
    [
    [1,2,3,4],
     [5,6,7,8]
    ],
     [
         [11,99,33,44],
          [55,66,77,88]
      ]
                  ])
p=np.argmax(array3D)
shape=array3D.shape
ind_max=np.unravel_index(p,shape)
ind_max

(np.int64(1), np.int64(0), np.int64(1))

In [ ]:
#itering over numpy arrays all element visit one by one
#we can use loop
array1D=np.array([1,2,3,4,5,6,7])
for i in array1D:
  print(i*i)
  print(i)

1
1
4
2
9
3
16
4
25
5
36
6
49
7


In [ ]:
#2d array
#we can use a nested for loop to itrate over 2D array
#the outer loop iterates over the outer array
#ineer loop iterates over the outer array
array2D=np.array([[1,2,3,4],[5,5,6,7],[8,8,7,9]])
for i in array2D:
  print(i)

[1 2 3 4]
[5 5 6 7]
[8 8 7 9]


In [ ]:
for i in array2D:
  for j in i:
    print(j)

1
2
3
4
5
5
6
7
8
8
7
9


In [ ]:
array3D=np.array([
    [
    [1,2,3,4],
     [5,6,7,8]
    ],
     [
         [11,99,33,44],
          [55,66,77,88]
      ]
                  ])
for i in array3D:
  for j in i:
    for k in j:
      print(k)

1
2
3
4
5
6
7
8
11
99
33
44
55
66
77
88


In [ ]:
#Adding  matrices together
a=np.array([
    [0,1],[1,2]
])
b=np.array([
    [2,3],[4,5]
])
print(a+b)

[[2 4]
 [5 7]]


In [ ]:
#adding 10 to each element
print(a+10)

[[10 11]
 [11 12]]


In [ ]:
#subtraction
print(a-2)

[[-2 -1]
 [-1  0]]


In [ ]:
#division
print(a/2)

[[0.  0.5]
 [0.5 1. ]]


In [ ]:
#multiplaction of two matrix
print(np.matmul(a,b))

[[ 4  5]
 [10 13]]


In [ ]:
#power
print(b**2)

[[ 4  9]
 [16 25]]


In [ ]:
m1=np.array([
    [1,2,3],[4,5,6]
])
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#tanspose to convert 3 row and 2 column
print(m1.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
data=np. array([10,20,30,40])
mean_val=np.mean(data)
print('mean=',mean_val)

mean= 25.0


In [ ]:
#mean and meedion
data=np. array([10,20,30,40])
mean_val=np.mean(data)
print('mean=',mean_val)
med_val=np.median(data)
print('median=',med_val)

mean= 25.0
median= 25.0


In [ ]:
#varienceand stander diviosuionm
data=np. array([10,20,30,40,50])
variance=np.var(data)
std_dev=np.std(data)
print('vatiance',variance)
print('std_dev',std_dev)

vatiance 200.0
std_dev 14.142135623730951


In [ ]:
import numpy as np